const Subjects = {
  first: [
    { name: "국어", value: "01" },
    { name: "수학", value: "02" },
    { name: "영어", value: "03" },
    { name: "한국사", value: "04" },
    { name: "통합 사회", value: "05" },
    { name: "통합 과학", value: "06" },
    { name: "한문 I", value: "12" },
    { name: "기술 가정", value: "11" },
  ],
  second: [
    { name: "문학", value: "22" },
    { name: "독서", value: "21" },
    { name: "수학", value: "24" },
    { name: "영어", value: "26" },
    { name: "윤리와 사상", value: "32" },
    { name: "세계사", value: "29" },
    { name: "한국 지리", value: "28" },
    { name: "경제", value: "30" },
    { name: "정치와 법", value: "31" },
    { name: "물리학 I", value: "34" },
    { name: "화학 I", value: "35" },
    { name: "생명과학 I", value: "36" },
    { name: "지구과학 I", value: "37" },
    { name: "심화국어", value: "23" },
    { name: "기하", value: "25" },
    { name: "영어권 문화", value: "27" },
    { name: "일본어 I", value: "42" },
    { name: "중국어 I", value: "44" },
    { name: "프랑스어 I", value: "43" },
  ],
  third: [
    { name: "화법과 작문", value: "51" },
    { name: "언어와 매체", value: "52" },
    { name: "영어 독해와 작문", value: "56" },
    { name: "영어 회화", value: "561" },
    { name: "미적분", value: "53" },
    { name: "중국어 II", value: "75" },
    { name: "일본어 II", value: "73" },
    { name: "프랑스어 II", value: "74" },
    { name: "확률과 통계", value: "54" },
    { name: "생활과 윤리", value: "60" },
    { name: "동아시아사", value: "58" },
    { name: "세계지리", value: "57" },
    { name: "여행지리", value: "61" },
    { name: "사회문화", value: "59" },
    { name: "물리학 II", value: "62" },
    { name: "화학 II", value: "63" },
    { name: "생명과학 II", value: "64" },
    { name: "지구과학 II", value: "65" },
    { name: "음악 감상과 비평", value: "69" },
    { name: "경제수학", value: "55" },
  ],
};

module.exports = { Subjects };
