const events = [
  {
    title: "입학식(1, 자율①②③)",
    allDay: "true",
    start: "2022-03-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "시업식(2,3, 자율①②③)",
    allDay: "true",
    start: "2022-03-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "흡연예방교육(자율⑤)",
    allDay: "true",
    start: "2022-03-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "학교폭력예방교육(자율⑥)",
    allDay: "true",
    start: "2022-03-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-03-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "1학기 정부회장선거(자율⑤)",
    allDay: "true",
    start: "2022-03-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "도박예방교육(자율⑥)",
    allDay: "true",
    start: "2022-03-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "학부모 총회",
    allDay: "true",
    start: "2022-03-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(자율⑤)",
    allDay: "true",
    start: "2022-03-18",
    display: "list-item",
    editable: false,
  },
  {
    title: "지진대피교육(자율⑥)",
    allDay: "true",
    start: "2022-03-18",
    display: "list-item",
    editable: false,
  },
  {
    title: "결핵검사(3)",
    allDay: "true",
    start: "2022-03-21",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가",
    allDay: "true",
    start: "2022-03-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-03-25",
    display: "list-item",
    editable: false,
  },
  {
    title: "선배와의 멘토링(3)",
    allDay: "true",
    start: "2022-03-25",
    display: "list-item",
    editable: false,
  },
  {
    title: "전공심화탐구 1차 안내",
    allDay: "true",
    start: "2022-03-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "상담주간(28일~1일)",
    allDay: "true",
    start: "2022-03-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "소변검사",
    allDay: "true",
    start: "2022-03-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "흡연음주예방교육(자율⑤⑥)",
    allDay: "true",
    start: "2022-04-01",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-04-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "세계 책의 날",
    allDay: "true",
    start: "2022-04-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가(3)",
    allDay: "true",
    start: "2022-04-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "인권교육(자율⑤⑥)",
    allDay: "true",
    start: "2022-04-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-04-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-04-21",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-04-22",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-04-25",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-04-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-04-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "지구의 날 맞이 기후변화행동 캠페인(1)",
    allDay: "true",
    start: "2022-04-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "봉사활동사전교육(봉사⑤⑥)",
    allDay: "true",
    start: "2022-04-29",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학탐구토론 페스티벌 예선(1,2)",
    allDay: "true",
    start: "2022-04-29",
    display: "list-item",
    editable: false,
  },
  {
    title: "페탕크축제(3)",
    allDay: "true",
    start: "2022-04-29",
    display: "list-item",
    editable: false,
  },
  {
    title: "교육 실습(2일~27일)",
    allDay: "true",
    start: "2022-05-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학탐구토론 페스티벌 본선(1,2)",
    allDay: "true",
    start: "2022-05-03",
    display: "list-item",
    editable: false,
  },
  {
    title: "그림그리기한마당(1, 자율①②③)",
    allDay: "true",
    start: "2022-05-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "백일장(2, 자율①②③)",
    allDay: "true",
    start: "2022-05-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "현장체험학습(3, 자율①②③)",
    allDay: "true",
    start: "2022-05-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "재량휴업일",
    allDay: "true",
    start: "2022-05-06",
    display: "list-item",
    editable: false,
  },
  {
    title: "전공심화탐구 2차 안내",
    allDay: "true",
    start: "2022-05-09",
    display: "list-item",
    editable: false,
  },
  {
    title: "독서캠프(1,2)",
    allDay: "true",
    start: "2022-05-10",
    display: "list-item",
    editable: false,
  },
  {
    title: "독서캠프(1,2)",
    allDay: "true",
    start: "2022-05-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "건강검진(1)",
    allDay: "true",
    start: "2022-05-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "플로깅활동(1, 봉사⑤⑥)",
    allDay: "true",
    start: "2022-05-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "심폐소생술교육(2,3, 자율⑤⑥)",
    allDay: "true",
    start: "2022-05-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "성희롱성폭력예방교육(1,3, 자율⑤⑥)",
    allDay: "true",
    start: "2022-05-20",
    display: "list-item",
    editable: false,
  },
  {
    title: "플로깅활동(2, 봉사⑤⑥)",
    allDay: "true",
    start: "2022-05-20",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(1, 자율⑤⑥)",
    allDay: "true",
    start: "2022-05-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "성희롱성폭력예방교육(2, 자율⑤⑥)",
    allDay: "true",
    start: "2022-05-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "봉사활동(3, 봉사⑤⑥)",
    allDay: "true",
    start: "2022-05-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-05-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "수요일 수업",
    allDay: "true",
    start: "2022-05-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "논술문쓰기대회(3)",
    allDay: "true",
    start: "2022-05-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "외교아카데미",
    allDay: "true",
    start: "2022-06-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "사회탐구경시대회(3, 일사, 지리, 윤리, 역사)",
    allDay: "true",
    start: "2022-06-03",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-06-03",
    display: "list-item",
    editable: false,
  },
  {
    title: "대수능모의평가(3)",
    allDay: "true",
    start: "2022-06-09",
    display: "list-item",
    editable: false,
  },
  {
    title: "수학경시대회(3, 확률과 통계, 미적분)",
    allDay: "true",
    start: "2022-06-10",
    display: "list-item",
    editable: false,
  },
  {
    title: "장애인식개선교육(자율⑤)",
    allDay: "true",
    start: "2022-06-10",
    display: "list-item",
    editable: false,
  },
  {
    title: "인터넷중독예방교육(자율⑥)",
    allDay: "true",
    start: "2022-06-10",
    display: "list-item",
    editable: false,
  },
  {
    title: "학생회장선거(자율⑤⑥)",
    allDay: "true",
    start: "2022-06-17",
    display: "list-item",
    editable: false,
  },
  {
    title: "아동학대예방교육(자율⑤)",
    allDay: "true",
    start: "2022-06-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "학급자치(1, 자율⑥)",
    allDay: "true",
    start: "2022-06-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(2,3, 자율⑥)",
    allDay: "true",
    start: "2022-06-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-06-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사",
    allDay: "true",
    start: "2022-06-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사",
    allDay: "true",
    start: "2022-06-29",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사",
    allDay: "true",
    start: "2022-06-30",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사",
    allDay: "true",
    start: "2022-07-01",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사",
    allDay: "true",
    start: "2022-07-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학경시대회(3, 물리)",
    allDay: "true",
    start: "2022-07-05",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가(3)",
    allDay: "true",
    start: "2022-07-06",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학경시대회(3, 화학)",
    allDay: "true",
    start: "2022-07-07",
    display: "list-item",
    editable: false,
  },
  {
    title: "2학기 정부회장선거(자율⑤)",
    allDay: "true",
    start: "2022-07-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "학급자치(1, 자율⑥)",
    allDay: "true",
    start: "2022-07-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(2,3, 자율⑥)",
    allDay: "true",
    start: "2022-07-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "제2외국어융합큐브챌린지(2, 불어, 일어, 중어)",
    allDay: "true",
    start: "2022-07-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학경시대회(3, 생물)",
    allDay: "true",
    start: "2022-07-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "자유적교육과정운영(11일~15일)",
    allDay: "true",
    start: "2022-07-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "인문융합아카데미(1,2)",
    allDay: "true",
    start: "2022-07-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학경시대회(3, 지구과학)",
    allDay: "true",
    start: "2022-07-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "인문융합아카데미(1,2)",
    allDay: "true",
    start: "2022-07-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "인문융합아카데미(1,2)",
    allDay: "true",
    start: "2022-07-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "영어종합발표회",
    allDay: "true",
    start: "2022-07-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-07-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학아카데미",
    allDay: "true",
    start: "2022-07-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-07-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "인문융합아카데미(1,2)",
    allDay: "true",
    start: "2022-07-18",
    display: "list-item",
    editable: false,
  },
  {
    title: "전공심화탐구 발표회(3)",
    allDay: "true",
    start: "2022-07-18",
    display: "list-item",
    editable: false,
  },
  {
    title: "방학식(자율①②③)",
    allDay: "true",
    start: "2022-07-20",
    display: "list-item",
    editable: false,
  },
  {
    title: "개학",
    allDay: "true",
    start: "2022-08-17",
    display: "list-item",
    editable: false,
  },
  {
    title: "학교폭력예방교육(자율⑤)",
    allDay: "true",
    start: "2022-08-19",
    display: "list-item",
    editable: false,
  },
  {
    title: "과학탐구발표페스티벌(1,2)",
    allDay: "true",
    start: "2022-08-19",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-08-19",
    display: "list-item",
    editable: false,
  },
  {
    title: "상담주간(22일~25일)",
    allDay: "true",
    start: "2022-08-22",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(1, 자율⑤)",
    allDay: "true",
    start: "2022-08-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "아동학대예방교육(1, 자율⑤)",
    allDay: "true",
    start: "2022-08-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "학급자치(2,3, 자율⑤⑥)",
    allDay: "true",
    start: "2022-08-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "리더십캠프",
    allDay: "true",
    start: "2022-08-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가(1,2)",
    allDay: "true",
    start: "2022-08-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "대수능모의평가(3)",
    allDay: "true",
    start: "2022-08-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-09-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "독서논술한마당(1,2)",
    allDay: "true",
    start: "2022-09-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "학교도서관의 날",
    allDay: "true",
    start: "2022-09-05",
    display: "list-item",
    editable: false,
  },
  {
    title: "학교홍보UCC 한마당",
    allDay: "true",
    start: "2022-09-08",
    display: "list-item",
    editable: false,
  },
  {
    title: "월요일 수업",
    allDay: "true",
    start: "2022-09-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "심폐소생술교육(1, 자율⑤⑥)",
    allDay: "true",
    start: "2022-09-16",
    display: "list-item",
    editable: false,
  },
  {
    title: "인권교육(2,3, 자율⑤⑥)",
    allDay: "true",
    start: "2022-09-16",
    display: "list-item",
    editable: false,
  },
  {
    title: "성매매가정폭력예방교육(자율⑤⑥)",
    allDay: "true",
    start: "2022-09-23",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-09-23",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-09-30",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-10-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-10-05",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-10-06",
    display: "list-item",
    editable: false,
  },
  {
    title: "중간고사",
    allDay: "true",
    start: "2022-10-07",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가(3)",
    allDay: "true",
    start: "2022-10-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "국제리더양성캠프(1,2)",
    allDay: "true",
    start: "2022-10-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "페탕크축제(1,2)",
    allDay: "true",
    start: "2022-10-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "장애인식개선교육(자율⑤)",
    allDay: "true",
    start: "2022-10-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "흡연예방교육(자율⑥)",
    allDay: "true",
    start: "2022-10-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "국제리더양성캠프(1,2)",
    allDay: "true",
    start: "2022-10-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "학급별현장체험(1,2, 자율①②③④)",
    allDay: "true",
    start: "2022-10-18",
    display: "list-item",
    editable: false,
  },
  {
    title: "학부모 수업 공개",
    allDay: "true",
    start: "2022-10-19",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-10-21",
    display: "list-item",
    editable: false,
  },
  {
    title: "인권교육(1, 자율⑤⑥)",
    allDay: "true",
    start: "2022-10-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "아동학대예방교육(2,3, 자율⑤)",
    allDay: "true",
    start: "2022-10-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(2,3, 자율⑥)",
    allDay: "true",
    start: "2022-10-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "토론한마당(1,2)",
    allDay: "true",
    start: "2022-10-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "전공심화탐구 발표회(1,2)",
    allDay: "true",
    start: "2022-10-31",
    display: "list-item",
    editable: false,
  },
  {
    title: "소방대피교육(자율⑤)",
    allDay: "true",
    start: "2022-11-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "약물오남용예방교육(자율⑥)",
    allDay: "true",
    start: "2022-11-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "수학페스티벌(1)",
    allDay: "true",
    start: "2022-11-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "다시만난수학(2)",
    allDay: "true",
    start: "2022-11-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-11-04",
    display: "list-item",
    editable: false,
  },
  {
    title: "생명존중교육(자율⑤⑥)",
    allDay: "true",
    start: "2022-11-11",
    display: "list-item",
    editable: false,
  },
  {
    title: "대학수학능력시험(3)",
    allDay: "true",
    start: "2022-11-17",
    display: "list-item",
    editable: false,
  },
  {
    title: "재량휴업일(1,2)",
    allDay: "true",
    start: "2022-11-17",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(3)",
    allDay: "true",
    start: "2022-11-22",
    display: "list-item",
    editable: false,
  },
  {
    title: "전국연합학력평가(1,2)",
    allDay: "true",
    start: "2022-11-23",
    display: "list-item",
    editable: false,
  },
  {
    title: "재량휴업일(3)",
    allDay: "true",
    start: "2022-11-23",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(3)",
    allDay: "true",
    start: "2022-11-24",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(3)",
    allDay: "true",
    start: "2022-11-25",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(3)",
    allDay: "true",
    start: "2022-11-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(3)",
    allDay: "true",
    start: "2022-11-29",
    display: "list-item",
    editable: false,
  },
  {
    title: "인터넷중독예방교육(자율⑤)",
    allDay: "true",
    start: "2022-12-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "도박예방교육(자율⑥)",
    allDay: "true",
    start: "2022-12-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-12-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "2학년 벌점경감청소",
    allDay: "true",
    start: "2022-12-07",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(1,2)",
    allDay: "true",
    start: "2022-12-09",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(1,2)",
    allDay: "true",
    start: "2022-12-12",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(1,2)",
    allDay: "true",
    start: "2022-12-13",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(1,2)",
    allDay: "true",
    start: "2022-12-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "기말고사(1,2)",
    allDay: "true",
    start: "2022-12-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "동아리⑤⑥",
    allDay: "true",
    start: "2022-12-16",
    display: "list-item",
    editable: false,
  },
  {
    title: "2학년 벌점경감청소",
    allDay: "true",
    start: "2022-12-20",
    display: "list-item",
    editable: false,
  },
  {
    title: "2학년 벌점경감청소",
    allDay: "true",
    start: "2022-12-21",
    display: "list-item",
    editable: false,
  },
  {
    title: "축제(동아리⑤⑥⑦)",
    allDay: "true",
    start: "2022-12-23",
    display: "list-item",
    editable: false,
  },
  {
    title: "연극발표주간(1)(26일~29일)",
    allDay: "true",
    start: "2022-12-26",
    display: "list-item",
    editable: false,
  },
  {
    title: "동계스포츠한마당",
    allDay: "true",
    start: "2022-12-27",
    display: "list-item",
    editable: false,
  },
  {
    title: "월요일 수업",
    allDay: "true",
    start: "2022-12-28",
    display: "list-item",
    editable: false,
  },
  {
    title: "방학식(자율①②③)",
    allDay: "true",
    start: "2022-12-30",
    display: "list-item",
    editable: false,
  },
  {
    title: "교직원 회의",
    allDay: "true",
    start: "2022-12-30",
    display: "list-item",
    editable: false,
  },
  {
    title: "목요일 수업",
    allDay: "true",
    start: "2023-02-01",
    display: "list-item",
    editable: false,
  },
  {
    title: "종업식(1,2, 자율①②③)",
    allDay: "true",
    start: "2023-02-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "졸업식(3, 자율①②③)",
    allDay: "true",
    start: "2023-02-02",
    display: "list-item",
    editable: false,
  },
  {
    title: "신학년 집중준비 기간",
    allDay: "true",
    start: "2023-02-14",
    display: "list-item",
    editable: false,
  },
  {
    title: "신학년 집중준비 기간",
    allDay: "true",
    start: "2023-02-15",
    display: "list-item",
    editable: false,
  },
  {
    title: "신학년 집중준비 기간",
    allDay: "true",
    start: "2023-02-16",
    display: "list-item",
    editable: false,
  },
];

export default events;
